### ISSUE TITLE
need update

### ISSUE THREAD

**Issue by panikajoreserv** [willbraun/linkedin-message-preview#1]
not work now

**Comment by willbraun** [comment]
Found the issue, LinkedIn had updated a class name. I fixed this in version 1.0.1. Waiting now for Google to approve the new version.

**Comment by willbraun** [comment]
Google approved the new version, it should be working now.

**Comment by panikajoreserv** [comment]
can you make the same script only for twitter?

**Comment by willbraun** [comment]
I can look into that

**Comment by willbraun** [comment]
@panikajoreserv I created a new extension called X Message Preview [here](https://chromewebstore.google.com/detail/x-message-preview/gpapcaklggahkdlafidianelmppffcad). If you like these extensions, could you please leave a good review and rate 5 stars on each of them?
